# Generated by Django 3.1.3 on 2021-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yetishtirilayotgan_mahsulotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='yetishtirilayotgan_mahsulotlar')),
                ('nomi', models.CharField(max_length=100)),
                ('sana', models.DateField()),
                ('malumot', models.TextField()),
            ],
        ),
    ]
